# Generated by Django 5.0.6 on 2024-05-23 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_tracker', '0001_initial'),
        ('users', '0002_position_remove_user_username_user_phone_user_tasks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tasks',
            field=models.ManyToManyField(blank=True, null=True, to='task_tracker.task', verbose_name='задачи'),
        ),
    ]
