# Generated by Django 5.0.6 on 2024-05-23 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_tracker', '0001_initial'),
        ('users', '0003_alter_user_tasks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tasks',
            field=models.ManyToManyField(blank=True, to='task_tracker.task', verbose_name='задачи'),
        ),
    ]
